name: Generate Sitemap

on:
  workflow_dispatch:      # agar bisa dijalankan manual dari tab "Actions"
  push:
    branches: [main]      # tetap jalan kalau ada push ke main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # WAJIB agar bisa push commit ke repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: "https://resta-travel.github.io"  # pastikan ini cocok dengan GitHub Pages kamu

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --cached --quiet || git commit -m "Update sitemap.xml"
          git push
